import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  container: {
    flex: 1,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    paddingBottom: 5,
    paddingTop: 20,
  },
  backButton: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: 10,
    borderRadius: 12,
  },
  backIcon: {
    width: 24,
    height: 24,
    tintColor: '#fff',
  },
  headerTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
  },
  headerRightPlaceholder: {
    width: 44,
  },
  fab: {
    position: 'absolute',
    right: 28,
    bottom: 36,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#13aff9',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 6,
    elevation: 6,
  },
  fabIcon: {
    width: 36,
    height: 36,
    resizeMode: 'contain',
    tintColor: '#13aff9',
  },
  cardsContainer: {
    padding: 16,
    paddingBottom: 120,
    gap: 16,
  },
  card: {
    flex: 1,
    minHeight: 200,
    margin: 8,
    borderRadius: 18,
    padding: 16,
    paddingBottom: 36,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.10,
    shadowRadius: 4,
    elevation: 2,
  },
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 8,
  },
  cardTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginRight: 8,
    flex: 1,
    minWidth: 0,
  },
  cardTitleIcon: {
    width: 22,
    height: 22,
    marginRight: 4,
    tintColor: '#174ea6',
    resizeMode: 'contain',
  },
  cardDateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginLeft: 8,
    maxWidth: 110,
    flexShrink: 1,
  },
  cardDateIcon: {
    width: 18,
    height: 18,
    marginRight: 2,
    tintColor: '#174ea6',
    resizeMode: 'contain',
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#174ea6',
    flex: 1,
    textAlign: 'left',
    minWidth: 0,
  },
  cardDate: {
    fontSize: 14,
    color: '#174ea6',
    fontWeight: 'bold',
    textAlign: 'right',
    marginLeft: 4,
    flexShrink: 1,
    maxWidth: 80,
    overflow: 'hidden',
  },
  cardText: {
    fontSize: 15,
    color: '#333',
    flex: 1,
  },
  emptyText: {
    color: '#fff',
    fontSize: 16,
    textAlign: 'center',
    marginTop: 40,
    opacity: 0.7,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '85%',
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 24,
    alignItems: 'stretch',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 8,
    elevation: 8,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#13aff9',
    marginBottom: 18,
    textAlign: 'center',
  },
  modalLabel: {
    fontSize: 15,
    color: '#333',
    marginBottom: 4,
    marginTop: 10,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#e3e3e3',
    borderRadius: 10,
    padding: 10,
    fontSize: 15,
    color: '#222',
    backgroundColor: '#f7f7f7',
    marginBottom: 8,
  },
  modalTextarea: {
    minHeight: 70,
    textAlignVertical: 'top',
  },
  modalButtonRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 16,
    gap: 10,
  },
  modalButton: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 8,
    backgroundColor: '#eee',
    marginLeft: 8,
  },
  modalButtonText: {
    fontWeight: 'bold',
    color: '#13aff9',
    fontSize: 15,
  },
  deleteButton: {
    position: 'absolute',
    right: 0,
    bottom: 3,
    padding: 8,
  },
  deleteIcon: {
    width: 20,
    height: 20,
    tintColor: '#174ea6',
  },
  deleteIconBg: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e6f3fa',
    alignItems: 'center',
    justifyContent: 'center',
  },
  suggestionsBox: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e3e3e3',
    marginBottom: 8,
    maxHeight: 140,
    overflow: 'hidden',
  },
  suggestionItem: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  suggestionText: {
    color: '#13aff9',
    fontSize: 15,
  },
  selectedDrugsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 8,
  },
  drugTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e6f3fa',
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 4,
    marginRight: 0,
    marginBottom: 0,
    maxWidth: '90%',
  },
  drugTagText: {
    color: '#13aff9',
    fontSize: 14,
    marginRight: 4,
    flexShrink: 1,
    flexWrap: 'wrap',
    maxWidth: '100%',
  },
  removeDrugText: {
    color: '#13aff9',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 2,
    marginTop: -2,
  },
  cardDivider: {
    width: '100%',
    height: 2,
    backgroundColor: 'rgba(23, 78, 166, 0.3)',
    borderRadius: 1,
    marginTop: 10,
    alignSelf: 'center',
  },
  drugTagRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
    marginBottom: 4,
  },
  drugTagIconBg: {
    width: 36,
    height: 36,
    borderRadius: 100,
    backgroundColor: '#e6f3fa',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  drugTagIcon: {
    width: 24,
    height: 24,
    tintColor: '#174ea6',
    resizeMode: 'contain',
  },
});

export default styles;
