import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  title: {
    fontSize: 32,
    color: '#fff',
    fontWeight: 'bold',
    marginBottom: 32,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  input: {
    width: 320,
    maxWidth: '100%',
    backgroundColor: 'rgba(0,0,0,0.18)',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    fontSize: 16,
    marginBottom: 16,
    color: '#fff',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  button: {
    width: 320,
    maxWidth: '100%',
    backgroundColor: 'rgba(19, 175, 249, 0.7)',
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 8,
    marginBottom: 20,
  },
  buttonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
  linksRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: 320,
    maxWidth: '100%',
    gap: 12,
  },
  linkButton: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.13)',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  linkText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
  },
  socialContainer: {
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 8,
  },
  socialLabel: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 10,
    textAlign: 'center',
    letterSpacing: 0.1,
  },
  socialRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 24,
  },
  socialButton: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: 'rgba(255,255,255,1)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.13,
    shadowRadius: 4,
    elevation: 3,
  },
  socialIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    resizeMode: 'cover',
    overflow: 'hidden',
  },
  socialDivider: {
    width: 320,
    height: 2,
    backgroundColor: 'rgba(255,255,255,0.25)',
    borderRadius: 1,
    marginTop: 2,
    marginBottom: 16,
    alignSelf: 'center',
  },
});

export default styles;
